url: "https://www.erlang.org"
baseurl: "" # the subpath of your site
title: "Erlang/OTP" # the name of your site
description: "The official home of the Erlang Programming Language"

plugins:
  - jekyll-feed
  - jekyll-liquify

collections:
  news:
    output: true
    permalink: /:collection/:path
    sort_by: date
  releases:
    output: true
    permalink: /downloads/:path
    sort_by: release
  patches:
    output: true
    permalink: /:collection/:path
    sort_by: tag_name
  posts:
    output: true
    permalink: /blog/:title/
  eeps:
    output: true
    permalink: /:collection/:path
  examples:
    output: false
  bugs:
    output: true
    permalink: /:collection/:path

feed:
  collections:
    news:
      path: "/news.xml"
    posts:
      path: "/blog.xml"

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

include:
  - _redirects
  - .well-known
  - _headers
exclude:
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - tsconfig.json
  - webpack.json
  - otp_versions.table
  - Gemfile*
  - _scripts/
  - _clones/
  - _news/README.md
  - _posts/README.md
  - _releases/README.md
  - assets/doc-search*
  - docs/doc
  - _patches/releases.json

## We use the kramdown renderer as it gives us better possibilities
## to configure how it should work and is used by many more project.
##
## I did experients to use commonmark instead, but the syntax
## highlighting of code segments did not work as expected.
kramdown:
  ## All syntax highlighting is done via javascript
  syntax_highlighter: nil
